In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('./data/p1_weight_sorted.csv')

# Writing filtering functions

In [3]:
def not_in_word(df, letter):
    print(f"Letter {letter} not in word")
    for word in df['words']:
        if letter in word:
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

In [4]:
def not_at(df, letter,at):
    at=at-1
    print(f"Letter {letter} not at place {at}")
    for word in df['words']:
        if letter == word[at] or letter not in word:
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

In [5]:
def at(df, letter,at):
    print(f"Letter {letter} is at place {at}")
    at=at-1
    for word in df['words']:
        if letter != word[at] or letter not in word:
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

# Writing Guess fucntion

In [6]:
def guess(word,color):
    for i,letter in enumerate(word):
        if color[i]=='r':
            not_in_word(df,letter)
        elif color[i]=='g':
            at(df,letter,i+1)
        elif color[i]=='y':
            not_at(df,letter,i+1)

In [7]:
word=input("Enter Word: ")
color=input("Enter colors: ")
guess(word,color)

Enter Word:
Enter colors:

In [8]:
df

,words,weightage,a,b,c,d,e,f,g,h,...,q,r,s,t,u,v,w,x,y,z
0,esses,0.513706,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,sessa,0.503346,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,sasse,0.503346,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,asses,0.503346,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,sease,0.503299,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12967,muzzy,0.114539,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
12968,whizz,0.114493,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,1
12969,huzzy,0.111209,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,1,1
12970,buzzy,0.109158,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,1
12971,fuzzy,0.101264,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,1