In [1]:
import pandas as pd

In [2]:
df_words=pd.read_csv('./data/p1_weight_sorted.csv')

In [3]:
df_words

       words  weightage
0      esses   0.513706
1      sessa   0.503346
2      sasse   0.503346
3      asses   0.503346
4      sease   0.503299
...      ...        ...
12967  muzzy   0.114539
12968  whizz   0.114493
12969  huzzy   0.111209
12970  buzzy   0.109158
12971  fuzzy   0.101264

[12972 rows x 2 columns]

# Writing filtering functions

In [4]:
inword=''

In [11]:
def not_in_word(df, letter,at):
    global inword
    print(inword)
    print(f"Letter {letter} not in word")
    if letter in inword:
        print(f"Letter {letter} is in the word so not deleting")
        not_at(df,letter,at)
        return
    for word in df['words']:
        if letter in word:
            if word =='green':
                print(f'Dropping {word}')
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

In [12]:
def not_at(df, letter,at):
    global inword
    inword+=letter
    print(inword)
    at=at-1
    print(f"Letter {letter} not at place {at}")
    for word in df['words']:
        if letter == word[at] or letter not in word:
            if word =='green':
                print(f'Dropping {word}')
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

In [13]:
def at(df, letter,at):
    global inword
    inword+=letter
    print(inword)
    print(f"Letter {letter} is at place {at}")
    at=at-1
    for word in df['words']:
        if letter != word[at] or letter not in word:
            if word =='green':
                print(f'Dropping {word}')
            i=(df[df.words==word].index)
            df.drop(i,inplace=True)

# Writing Guess fucntion

In [14]:
def guess(df,word,color):
    for i,letter in enumerate(word):
        if color[i]=='r':
            not_in_word(df,letter,i+1)
        elif color[i]=='g':
            at(df,letter,i+1)
        elif color[i]=='y':
            not_at(df,letter,i+1)

In [15]:
def play():
    df=df_words.copy()
    for i in range(5):
        word=input("Enter Word: ")
        if word=='111':
            print("Congratulations...")
            break
            return
        color=input("Enter colors: ")
        guess(df,word,color)
        print(df.head())

In [17]:
play()

Enter Word: audio
Enter colors: yyrrr
ua
Letter a not at place 0
Dropping green
uau
Letter u not at place 1
uau
Letter d not in word
uau
Letter i not in word
uau
Letter o not in word
     words  weightage
384  sarus   0.400694
389  urase   0.400648
391  ureas   0.400648
393  ursae   0.400648
659  sauls   0.388560
Enter Word: urase
Enter colors: yryrg
uauu
Letter u not at place 0
uauu
Letter r not in word
uauua
Letter a not at place 2
uauua
Letter s not in word
uauuae
Letter e is at place 5
      words  weightage
4735  taupe   0.315711
5099  haute   0.311718
5259  taube   0.309667
6470  value   0.296454
6575  vaute   0.295282
Enter Word: taupe
Enter colors: rggrg
uauuae
Letter t not in word
uauuaea
Letter a is at place 2
uauuaeau
Letter u is at place 3
uauuaeau
Letter p not in word
uauuaeaue
Letter e is at place 5
      words  weightage
7617  gauge   0.284474
8445  mauve   0.274946
9157  gauze   0.265819
9361  gauje   0.263614
9505  fauve   0.261671
Enter Word: gauge
Enter colors: gggyg
uauuaeaueg
Letter g is at place 1
uauuaeauega
Letter a is at place 2
uauuaeauegau
Letter u is at place 3
uauuaeauegaug
Letter g not at place 3
uauuaeauegauge
Letter e is at place 5
      words  weightage
9157  gauze   0.265819
9361  gauje   0.263614
Enter Word: gauze
Enter colors: ggggg
uauuaeauegaugeg
Letter g is at place 1
uauuaeauegaugega
Letter a is at place 2
uauuaeauegaugegau
Letter u is at place 3
uauuaeauegaugegauz
Letter z is at place 4
uauuaeauegaugegauze
Letter e is at place 5
      words  weightage
9157  gauze   0.265819